# Generated by Django 4.0.3 on 2022-04-08 08:10
import os

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name=os.environ.get('DJ_GROUP_STUDENTS'))
    Group.objects.create(name=os.environ.get('DJ_GROUP_INSTRUCTORS'))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
